name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  # audio_query: ^0.0.2
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  google_fonts: ^6.1.0
  just_audio: ^0.9.36
  lottie: ^3.1.0
  objectbox: ^2.5.0
  objectbox_flutter_libs: ^2.5.0
  on_audio_query: ^2.9.0
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  riverpod_annotation: ^2.3.4
  scroll_to_hide: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  objectbox_generator: ^2.5.0
 

flutter:
  uses-material-design: true

  assets:
      - assets/lottie/
